### ISSUE TITLE
Design database scheme for TICCLAT

### ISSUE THREAD

**Issue by egpbos** [TICCLAT/ticclat#3]
- [ ] Requirement assessment
    - [x] Use cases #6
    - [ ] What is available? #2 
    - [ ] Example/benchmark queries: what should the database be able to do? #7
    - [ ] Interface with TICCL #8 
- [x] Write design
    - [x] Database schema
- [x] Ask Data SIG for input (when we have a decent draft design)

**Comment by jvdzwaan** [comment]
The base schema is complete, closing this issue...
